# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  # config.vm.synced_folder "./vagrant_data", "/vagrant_data"

  config.vm.define "abaddon" do |abaddon|
    abaddon.vm.box = "generic/ubuntu2204"
    abaddon.vm.hostname = "abaddon"
    abaddon.vm.network "private_network", ip: "10.66.66.20"

    abaddon.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 4096
    end
  end

end
